version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=josedev
      - POSTGRES_PASSWORD=dev1234
    ports:
      - 5432:5432
    volumes:
      - './postgres_data:/var/lib/postgresql/data'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=store_db
      - MYSQL_ROOT_PASSWORD=dev1234
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - './mysql_db_data:/var/lib/mysql'


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=dev1234
      - PMA_HOST=mysql
    ports:
      - 8080:80
